### ISSUE TITLE
Getting an error on setting up Reportserver environment using docker

### ISSUE THREAD

**Issue by visakhmurukes** [bitnami/bitnami-docker-reportserver#2]
Tried setting up docker image for reportserver and got below error message while browsing to ip address in browser getting an error as below
 
**ReportServer encountered an error while validating its environment**

1. Followed instructions as in 
https://hub.docker.com/r/bitnami/reportserver
2.  Once dockers are up tried accessing reportserver through http://ipname

Got error as in below screenshot
![RSError](https://user-images.githubusercontent.com/14180077/74132715-8b5c1480-4c00-11ea-8dd8-7e17b625af86.png)

**Comment by rafariossaa** [comment]
Hi @visakhmurukes ,
  Could you provide the full log of the `docker-compose up`  command ?

**Comment by visakhmurukes** [comment]
> Hi @visakhmurukes ,
> Could you provide the full log of the `docker-compose up` command ?

Thanks @rafariossaa  for the quick response

Please find attached the logs
[bitnami docker compose.log](https://github.com/bitnami/bitnami-docker-reportserver/files/4179864/bitnami.docker.compose.log)

I also checked the attached MariaDB instance and couldnt find the metadata tables it was complaining about.

**Comment by rafariossaa** [comment]
That's weird. 
Could you share the docker file you are using ?
Could you also run `docker info` and `docker version` and provide the information returned ?.

**Comment by visakhmurukes** [comment]
> That's weird.
> Could you share the docker file you are using ?
> Could you also run `docker info` and `docker version` and provide the information returned ?.

Sorry for not responding sooner. Was held up with some other priorities
Actually I was not using any other dockerfile. Just was trying the standard docker compose from the project. 
docker version gives the below

![image](https://user-images.githubusercontent.com/14180077/75035459-f0e5b600-54c8-11ea-816f-cadc4e6da4f9.png)


and docker info gives this

![image](https://user-images.githubusercontent.com/14180077/75035553-28546280-54c9-11ea-828b-cff48a8f1d49.png)

**Comment by rafariossaa** [comment]
Hi,
  Could you run   `docker-compose down -v` ? This will remove the data volumes, hence all the data, and run `docker-compose up` again ?
  By the logs messages it seems that mariadb it is already initialized and maybe that is the problem.

**Comment by rafariossaa** [comment]
Due to inactivity, I am closing this issue.
