### ISSUE TITLE
Docker Image fails using Azure Container Instance

### ISSUE THREAD

**Issue by ghost** [bitnami/bitnami-docker-reportserver#3]
**Description**

Azure Container Instance not successfully running Docker image?

**Steps to reproduce the issue:**

1. Create Azure Container Instance
2. Specify docker pull path (bitnami/reportserver)
3. Hit "Create"

**Describe the results you received:**

Container provisioned correctly (See attached screenshots). Navigating to the FQDN results in connection timeout error. Looking at logs shows unable to connect to database.

**Describe the results you expected:**

I expected for reportserver to load. I am not using Docker Compose explicitly, but using the GUI in Azure to create a container instance and referencing the image from Docker Hub. I have done this several time with other apps\images from Docker hub with no issues. I have also tried increasing intance resources up to 4 vCPU and 16gb with the exact same results

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens using Azure Container Instances. Looking at the logs it doesn't seem to be able to connect to the database as well? Any help on how to provision this image in an Azure Container Instance would be greatly appreciated.

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
![1585422815607](https://user-images.githubusercontent.com/62811356/77831646-a968d000-70ed-11ea-8f95-9e6c74b630ef.png)
![1585422950525](https://user-images.githubusercontent.com/62811356/77831722-141a0b80-70ee-11ea-94fb-9e6896a0be97.png)
![1585423522761](https://user-images.githubusercontent.com/62811356/77831908-40825780-70ef-11ea-9449-fdada801bbb2.png)

**Comment by rafariossaa** [comment]
Hi,
  The reportserver container is waiting to the database to be ready.
  Have you configured the database backend ? You can configure the database backed setting environment variables, please take a look to https://github.com/bitnami/bitnami-docker-reportserver#user-content-use-an-existing-database .

**Comment by rafariossaa** [comment]
Hi,
 Due to inactivity, I am closing this issue.
 Please, don't hesitate to reopen it if needed.
