### ISSUE TITLE
Specify custom reportserver PORT?

### ISSUE THREAD

**Issue by iamakimmer** [bitnami/bitnami-docker-reportserver#4]
Is there a property I can use to override the default report server port of 8080?

**Comment by FraPazGal** [comment]
Hi @iamakimmer,

Thanks for your issue! Currently, our `reportserver` image doesn't support changing the default port. If you have looked at it, could you tell me if you found anything in reportserver's [official documentation](https://reportserver.net/en/documentation/)? I wasn't able to find anything related to that.
